#+TITLE: About Me
My name is Dan. I'm a data scientist at [[https://bit.io][bit.io]], where we offer the fastest and easiest way to get a
secure, private PostgreSQL database. In this role, I write and I work on internal analytics.

Prior to starting at bit.io, I was the Director of Data Analytics at the Guinn Center for Policy Priorities in Las Vegas, Nevada. In this role, I was responsible for conducting data-driven policy analysis and for supporting ongoing research and data analysis at the Guinn Center.

I received a B.A. in the History of Science at the University of Chicago. Following this, I worked for several years for Context Matters, Inc., a data analysis company focused on global pharmaceutical reimbursement policies and data. While working at Context Matters, I wrote extensively about drug pricing and reimbursement practices. I went on to receive an M.S. in Statistics from the University of Minnesota, Twin Cities. My thesis work comprised a simulation-based comparison of statistical tests for heterogeneity of risk difference between patient subgroups in clinical trials.

In 2018, I was a graduate research fellow in the Data Science for the Public Good program at the
Biocomplexity Institute of Virginia Tech. I have also worked on a variety of projects for for-profit and nonprofit organizations as a statistics and data science consultant
