#+TITLE: About Me

My name is Dan. I am a data scientist at bit.io, which offers the fastest way to
get a cloud PostgreSQL database. In my role, I use bit.io databases to manage
the data in various data science research projects. I've analyzed data and
written about topics such as [[https://innerjoin.bit.io/the-high-climate-cost-of-meat-oil-and-landfills-b7c674d1dd68][methane emissions]], [[https://innerjoin.bit.io/ask-a-bayesian-who-is-better-at-wordle-76a0e5199ed][Bayesian statistics]], [[https://innerjoin.bit.io/resignations-have-increased-every-year-since-2010-2b88b53c7f32][labor
turnover]], [[https://medium.com/the-inner-join/a-case-for-doubling-the-size-of-the-us-house-of-representatives-2799a5268920][the size of the House of Representatives]], and much more.

Prior to starting at bit.io, I was the Director of Data Analytics at the Guinn
Center for Policy Priorities in Las Vegas, Nevada. In this role, I was
responsible for conducting data-driven policy analysis and for supporting
ongoing research and data analysis at the Guinn Center. Most of my work a the
Guinn Center focused on public health, climate change, and the 2020 Census.

I received a B.A. in the History of Science at the University of Chicago
in 2013. Following this, I worked for several years for Context Matters, Inc., a
data analysis company focused on global pharmaceutical reimbursement policies
and data. While working at Context Matters, I wrote extensively about drug
pricing and reimbursement practices. I went on to receive an M.S. in Statistics
from the University of Minnesota, Twin Cities. My thesis work comprised a
simulation-based comparison of statistical tests for heterogeneity of risk
difference between patient subgroups in clinical trials.

In 2018, I was a graduate research fellow in the Data Science for the Public
Good program at the Biocomplexity Institute of Virginia Tech. I have also worked
on a variety of projects for for-profit and nonprofit organizations as a
statistics and data science consultant.
