* [[file:index.org][Daniel Liden]]

July 4, 2026

(No preview)
* [[file:archive.org][Posts Archive]]

July 4, 2026

(No preview)
* [[file:about.org][About Me]]

September 22, 2025

(No preview)
* [[file:notes.org][Notes and Drafts]]

March 30, 2024

(No preview)
* posts
** [[file:posts/20260228-harness-engineering.org][Harness Engineering]]

February 28, 2026

In the first couple of years of LLMs, we talked a lot about "prompt engineering": how to craft a /prompt/ just so in order to induce the LLM to do what we want. Since then, we've moved on to the more expansive "context engineering": how multiple available sources of context (chat history, file reads, web search results, etc.) should be combined to induce an agent to do what we want. Here, I'm writing about the even-more-expansive notion of "harness engineering": how do we orchestrate the whole loop of LLM invocations, tool calls, background process management, context retrieval, permission asks, etc., to get the agent to do what we want?
** [[file:posts/20251122-emacs-window-configs.org][Saving and Restoring Window Configurations in Emacs]]

November 22, 2025

When working in emacs, I often switch between different combinations of windows with different splits. For example, I might have one configuration with an org mode buffer with some notes alongside org-agenda, and another with a Python source file and a Python REPL. Before, I was switching between them by changing buffers and splits each time, which was cumbersome. Registers make it much simpler, and ~desktop-save-mode~ lets you persist window configurations across sessions.
** [[file:posts/20251001-mlflow-mcp-server.org][Using MLflow's MCP Server for Conversational Trace Analysis]]

October 1, 2025

MLflow 3.4 introduced an official MCP server that lets AI assistants like Claude interact directly with your MLflow traces. This post explores how to set it up when MLflow is installed in a virtual environment, and demonstrates practical usage with both Claude Desktop and Claude Code for debugging and analyzing GenAI application traces.
** [[file:posts/20250921-mcp-prompts-resources.org][Getting Started with Model Context Protocol Part 2: Prompts and Resources]]

September 21, 2025

In the first part of this series on Anthropic's Model Context Protocol, I showed how to define a very simple MCP server with one tool and install it to Claude Desktop. In this post, we will look at two more MCP concepts and learn how to use them: *resources*, which expose data and other content to models, and *prompts*, which are intended to allow users to select reusable prompt templates suited for certain tasks or workflows.
** [[file:posts/20250412-mcp-quickstart.org][Getting Started with Model Context Protocol Part 1: Add a Simple MCP Server to Claude Desktop]]

April 12, 2025

This post provides a simple, minimal example of setting up and using an MCP (model context protocol) server for use with Claude Desktop.

There are many MCP guides and tutorials and docs out there. In this one, I attempt to start with very simple implementations with as little complexity as possible in order to get started as quickly as possible.

Future posts will add more complexity, showing how to use additional MCP abstractions like prompts and resources, how to write an MCP client in Python, and how to use LLMs from other providers with MCPs.
** [[file:posts/20250330-emacs-debugging.org][Emacs Introspection and Debugging]]

March 23, 2025

If you use Emacs, you will eventually run into errors. Maybe a recent package update introduced some new issues with your system. Or some custom elisp you wrote runs into an edge case. Regardless of the cause, Emacs provides many tools for identifying the causes of errors and learning how to address them.

This post works through a recent issue I encountered with the ~eglot~ package and how I was able to identify and fix the issue using various introspection tools built into Emacs. It provides some general advice for how to use Emacs to learn about and debug issues with Emacs.
** [[file:posts/20240505-journal-persist.org][Persistent Elements in Daily Journals with Org Agenda]]

May 5, 2024

I use denote's [[https://protesilaos.com/emacs/denote#h:4a6d92dd-19eb-4fcc-a7b5-05ce04da3a92][journaling features]] to keep a daily project log, where I record whatever I'm working on, stray bits of knowledge, some TODOs, fleeting thoughts, etc.

In some cases, I want to refer back to these notes. But I (will) have a lot of these journal files. I don't want to search through them manually to find the name of that article, or that recommendation I jotted down, or whatever it was.

This post shows a quick solution to this issue using [[https://orgmode.org/worg/org-tutorials/org-custom-agenda-commands.html][org-agenda-custom-commands]] to make a custom view over specified tags in my journal files.
** [[file:posts/20240329-h2o-rag-data.org][Retrieving Data for the H2o RAG Benchmark]]

March 29, 2024

I was looking for a good dataset to use for comparing different models in a RAG application when I found [[https://www.reddit.com/r/LocalLLaMA/comments/1bpo5uo/rag_benchmark_of_databricksdbrx/][this post]] on Reddit. It compares a bunch of models on a collection of questions over a set of documents provided by [[https://h2o.ai][H2O.ai]].

I wasn't super interested in the benchmark, but the files (mostly pdfs, one mp3, jpg, other file types) interested me for use in my own testing. This short post shows how to get them using the scripts provided by h2o.ai.
** [[file:posts/20240325-org-clone-timeshift.org][Making headings for recurring tasks in org mode]]

March 25, 2024

This short post shows how to use the ~org-clone-subtree-with-time-shift~ command to make org headings for recurring tasks. I was recently trying to add a five-week class to my org agenda and I didn't want to manually create each heading and add or modify the timestamp. This approach made it very easy.
** [[file:posts/20231217-emacs-hooks.org][Introduction to Emacs Hooks]]

December 17, 2023

Today I was customizing the appearance of org files displayed with [[https://github.com/takaxp/org-tree-slide][org-tree-slide]]. In particular, I wanted to increase the font size and start [[https://github.com/rnkn/olivetti][Olivetti mode]] whenever I started ~org-tree-slide-mode~ and return everything to normal when I was done. This, I quickly discovered, required the use of [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Hooks.html][hooks]]. Hooks are not especially complicated, but they are useful and worth taking a few minutes to understand. This post will cover the basics of working with hooks in emacs.
** [[file:posts/20230709-yasnippet-chatgpt-shell.org][YASnippet for Prompt Templates for Chatgpt-Shell]]

July 9, 2023

The wonderful [[https://github.com/xenodium/chatgpt-shell][chatgpt-shell]] package by [[https://github.com/xenodium][Xenodium]] lets you interact with the gpt-3.5 and gpt-4
APIs in emacs via a handy shell built on top of ~comint-mode~. It also integrates
well with ~org-mode~.

I find that I tend to re-use a few prompt patterns for specific tasks. Yasnippet provides a great
way to create prompt /templates/ made up of some fixed component with placeholders
for user input. I can easily insert these prompt templates when working with
~chatgpt-shell~ to gain easy access to reusable, task-specific prompts. This post
describes how to start using Yasnippet for prompt templates for use with
~chatgpt-shell~.
** [[file:posts/20230428-ai-db-writing.org][Writing on AI and Postgres]]

June 1, 2023

Since this start of this year, I've been working on and writing about AI tools
for working with Postgres databases. Most of this work has involved finding
different ways to integrate ChatGPT (and previously Codex) with other tools and
workflows. I wanted to collect and share some of that writing here, as it's
related to a lot of the other things I write about on my personal blog.
** [[file:posts/20230310-chatgpt-julia-2.org][Using the ChatGPT API with Julia Part 2: Defining a Chat Struct]]

March 10, 2023

One of the things that makes working with the ChatGPT API a little different
from working with, e.g., the ~davinci-text-003~ model api is the need to maintain
the history of a given chat session. A Julia ~Struct~ containing the chat
history, coupled with a function that acts on that Struct, provides a good way
to work with the ChatGPT API.

For the basics of working with the ChatGPT API, check out [[file:20230303-chatgpt-julia.org][part 1]].
** [[file:posts/20230303-chatgpt-julia.org][Using the ChatGPT API with Julia Part 1: the HTTP.jl Library]]

March 4, 2023

This brief post shows the basics of using the Julia ~HTTP~ library to interact
with the OpenAI ChatGPT API, which was made public a few days ago. This post
will only include the minimum necessary detail for getting started with the
API. Future posts will go into a little more detail on how to send message
histories and engage more interactively with the API.
** [[file:posts/20221217-denote-quarto.org][Using Quarto Files with Denote]]

December 22, 2022

The latest release of [[https://protesilaos.com/emacs/denote][Denote]] (by the inimitable Protesilaos Stavrou) introduced
support for [[https://protesilaos.com/codelog/2022-10-30-demo-denote-custom-file-type/][custom file types]] in addition to the defaults, Org, Markdown+YAML,
Markdown+TOML, and plain text. This post shows how to add [[https://quarto.org/][Quarto]] files
(.qmd). Quarto, the successor to R Markdown, is "an open-source scientific and
technical publishing system" with support for Python, R, Julia, and
Observable. The setup detailed here will allow one to choose the .qmd filetype
when creating a new Denote file.
** [[file:posts/20220918-jq-example.org][Processing a JSON API Response with jq]]

September 18, 2022

There are countless ways of processing JSON data and converting it to different
formats. Historically, I've used Python and loaded the data into a Pandas
Dataframe for processing. This isn't really necessary for simple tasks,
though. Sometimes, a lightweight command line tool does the job just fine. Enter
~jq~. [[https://stedolan.github.io/jq/][jq]] is "like ~sed~ for JSON data." This post walks through an example of
downloading data from an API, extracting a few fields based on some conditions,
and converting the results to a CSV using ~jq~.
** [[file:posts/20220724-html5.org][Figures and Captions Don't Appear as Expected with Default Export Options]]

July 24, 2022

I noticed that some of the formatting on this site was a little off and some of
the org-mode components weren't being translated to HTML in quite the way I
expected. Fixing this was simple, but /finding/ the solution wasn't. In short, it
was necessary to set the ~org-html-doctype~ to ~html5~ (the default is
~xhtml-strict~). Furthermore, I set ~org-html-html5-fancy~ to ~t~. These ensure the
org export process takes advantage of block elements offered in the ~html5~
standard.
** [[file:posts/20220719-julia-plots.org][Basic Plotting in Julia]]

July 19, 2022

In this short post, I show one of the many ways of using Julia within emacs
org mode, and will describe some of the basic plotting functionality in Julia.
** [[file:posts/20220208-org-source.org][Org Mode Headlines in Org Source Blocks]]

February 8, 2022

When writing about org mode, one often wants to show what particular org
headline look like in terms of formatting, properties, tags, options,
etc,. However, even within a babel org source block, an org header will be
parsed and exported as a header. We can get around this by prepending the
headline with a comma. The comma won't show up when exported: all that is
exported is a nicely-formatted example of an org headline.
** [[file:posts/20220116-org-time.org][Task Repeaters in Org Mode]]

January 29, 2022

I recently started using org-mode to keep track of a few habits (morning
meditation, getting some sunlight and exercise before my morning coffee, etc.)
and needed to make use of org-mode's calendar features to do so. I've previously
set deadlines and scheduled dates for my ~TODO~ entries, but have seldom used
repeat intervals. My early attempts ( ~date +1d~) worked fine but required some
extra steps if I ever missed a day. This post discusses the ~.+~ and ~++~
-style repeat intervals, which allow more control over what happens when you
complete a task after the scheduled date.
** [[file:posts/20211209-R-babel.org][Org Babel Source Blocks for R]]

December 11, 2021

[[https://orgmode.org/worg/org-contrib/babel/intro.html][Org Babel]] is one of the best tools available for [[https://www-cs-faculty.stanford.edu/~knuth/lp.html][literate programming]]. As a data scientist, I use it
as a plain-text alternative to Jupyter notebooks. Org-mode files are much easier to track with
version control and don't require the overhead of a browser. There are tradeoffs: Jupyter notebooks
handle the display of different types of output (text results, images, interactive figures, etc.) in
a way that is both seamless and visually appealing. Displaying figures at all can be a challenge
when getting started with org-babel. This post covers the basics of using org-babel for common data
science tasks in R.
** [[file:posts/20211203-this-site.org][Made with Org-Mode]]

December 3, 2021

I finally made a personal site using org-mode's built-in ~ox-publish~ exporter.

I've written my personal website with org-mode for years (it is, after all, [[https://karl-voit.at/2017/09/23/orgmode-as-markup-only/][one of the most
reasonable markup languages to use for text]]). But until this point, I've used Hugo (with the ~ox-Hugo~
exporter). It worked fine, but it always seemed /just a little bit too complicated/ for my needs. I
wanted to find something where I could basically understand all of the components and where the gap
between my org-mode files and the published output was as small as possible. I wanted to focus more
on the writing and less on understanding the framework.
** [[file:posts/20211201-resources.org][Resources]]

December 2, 2021

Here are some resources to reference for building a simple site with org-mode. I've extensively
used the sites listed as models for building the present site and expect to continue to reference
them for some time.
** [[file:posts/20210514-pytorch-numerai.org][A Simple PyTorch Model for the Numerai Tournament]]

May 14, 2021

/This is another one from the archives. It covers how to train a basic PyTorch
model for use in the Numerai tournament, at least as it was in May 2021. See the original post [[https://pensive-wing-19c199.netlify.app/post/mlp-numerai-05082021/][here.]]/
** [[file:posts/20210213-urban-heat.org][Mapping Urban Heat by Census Tract in R]]

February 13, 2021

/Another one from the archives--this is one of my projects from my time at the Guinn Center, and something I very much wish I could have developed further: an analysis of urban heat in Las Vegas./
** [[file:posts/20190614-ml-yearning-review.org][Book Review: Machine Learning Yearning by Andrew Ng]]

June 14, 2019

/This is the first of a few posts I'm migrating from my old site, which you can
still find [[https://pensive-wing-19c199.netlify.app/][here]]. This is a review of Machine Learning Yearning by Andrew Ng./
* notes
** [[file:notes/20250425-admonition-demo.org][Styling Org Callouts for the Site]]

September 20, 2025

Quick walkthrough of the site’s new callout styling for Org blocks: see the raw markup, the rendered result, and the tiny bit of CSS/JS that makes it work.
** [[file:notes/20250308-registers-1.org][Navigating between points with registers]]

March 8, 2025

Registers provide a very easy way to navigate between different points in Emacs. This note briefly describes how to use them.
** [[file:notes/20241112-python-setup.org][Using Python in Emacs]]

November 12, 2024

I will keep this note up to date with details on how I use emacs for Python development.
** [[file:notes/20240821-uv.org][Python Package Management with uv]]

August 21, 2024

Yesterday (<2024-08-20 Tue>), Astral released [[https://astral.sh/blog/uv-unified-python-packaging][a bunch of updates]] to [[https://github.com/astral-sh/uv][uv]], their Python package/project manager, written in Rust. I've been using uv for the past month or two, mostly as a very fast drop-in replacement for venv and pip.

The new release expands uv into "an end-to-end solution for managing Python projects, command-line tools, single-file scripts, and even Python itself."

This post will very briefly explore the workflow I am most interested in—setting up an environment, installing packages, and specifying requirements.
** [[file:notes/20240818-answer-ai.org][Answer.ai, Claudette, and FastHTML]]

August 18, 2024

I just listened to the latest episode of the [[https://www.latent.space/p/answerai][Latent Space podcast]], which featured Jeremy Howard of [[https://www.fast.ai/][fast.ai]] fame. Fast.ai was my introduction to deep learning—or at least re-introduction following a brief and theory-oriented treatment of the topic in grad school—and the course and book remain among the best learning resources I have ever encountered. The podcast was a good reminder to look into the projects Howard and his team have been working on at [[https://www.answer.ai/][answer.ai]], "a new kind of AI R&D lab which creates practical end-user products based on foundational research breakthroughs."
** [[file:notes/20240709-python-readline.org][Python interpreter doesn't seem to support readline error in Emacs on MacOS]]

July 9, 2024

I was encountering this warning when trying to use Python in Emacs on Macos: ~Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "python3" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally.~ I found years of discussions on this issue, but no solutions. I also found that using Python installed with Conda instead of with virtualenv worked fine. From this, I narrowed down the root cause and found a working solution: (1) install the ~gnureadline~ Python package with ~pip install gnureadline~; (2) override the default readline in your virtual environment with ~python -m override_readline~.

In the rest of this note, I will briefly review the steps of the investigation that led me here. Scroll down to the Solution sectionif you're (understandably) not interested in the rest!
** [[file:notes/20240418-instructor-async.org][Asynchronous Instructor]]

April 18, 2024

In this example, I was extracting a list of topics from a list of 1000 JSON objects loaded as a list of Python dicts.

I used the Anthropic Haiku model.

Using the instructor library with the asynchronous Anthropic client makes it much faster to make a large number of calls to the Anthropic API fairly quickly. 
** [[file:notes/20240417-mlflow-qlora.org][Logging and Loading a QLoRA Model with MLflow]]

April 17, 2024

This is a minimal example of how to log an MLflow qlora model. It does not show any actual model training or data processing, just the basic process of saving the model.
** [[file:notes/20240416-torch-cuda-flash-attn.org][Troubleshooting Flash Attention Installation]]

April 16, 2024

I have repeatedly run into issues getting flash-attention working correctly with whatever version of PyTorch and CUDA I happen to be working with. I found a working pattern, at least for the platform I tend to be working on (Databricks). This note is a quick summary.
** [[file:notes/20240405-qlora-hf.org][Intro to QLoRA]]

April 5, 2024

I have a basic understanding of what QLoRA is, but given its popularity and apparent success, I am not nearly familiar enough with it. These are my notes on the Hugging Face blog post about QLoRA and quantization. Later, I will also make a note with some examples.
** [[file:notes/20240404-dbrx-mlflow.org][DBRX with MLflow]]

April 4, 2024

This note shows how to access Databricks foundation model APIs via OSS MLflow deployments server and via the MLflow OpenAI model flavor.
** [[file:notes/20240403-dbrx-instructor.org][Using the DBRX Model with Instructor]]

April 3, 2024

This note briefly demonstrates how to use the [[https://github.com/jxnl/instructor][Instructor]] library with the Databricks [[https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm][DBRX]] model via the Databricks Foundation Models API.
** [[file:notes/20240401-mlx-quickstart.org][MLX Quickstart]]

April 1, 2024

These are my notes on the [[https://ml-explore.github.io/mlx/build/html/usage/quick_start.html][MLX quick start guide and usage notes]]. It's a work in progress. Ultimately, I'm interested in learning what MLX will let me do with LLMs on my laptop. I might write something more substantial on that topic in the future. For now, you're probably better off consulting the docs yourself than looking at my notes on them.
** [[file:notes/20240330-raschka-torch-notes.org][PyTorch Review]]

March 31, 2024

This is a quick run through the appendix on PyTorch from Sebastian Raschka's [[https://www.manning.com/books/build-a-large-language-model-from-scratch][Build a Large Language Model (From Scratch)]] book, currently available via Manning's MEAP. I haven't spent an enormous amount of time with PyTorch in the last year or so, so it seemed worth the effort to work through it.
