* [[file:index.org][(2021-12-03) Daniel Liden's Home Page]]
(No preview)
* [[file:about.org][(2021-12-03) About Me]]
My name is Dan. I'm a data scientist at [[https://bit.io][bit.io]], where we offer the fastest and easiest way to get a
secure, private PostgreSQL database. In this role, I write and I work on internal analytics.

Prior to starting at bit.io, I was the Director of Data Analytics at the Guinn Center for Policy Priorities in Las Vegas, Nevada. In this role, I was responsible for conducting data-driven policy analysis and for supporting ongoing research and data analysis at the Guinn Center.
* [[file:archive.org][(2021-12-02) Posts Archive]]
(No preview)
* posts
** [[file:posts/20211203-this-site.org][(2021-12-03) Made with Org-Mode]]
I finally made a personal site using org-mode's built-in ~ox-publish~ exporter.

I've written my personal website with org-mode for years (it is, after all, [[https://karl-voit.at/2017/09/23/orgmode-as-markup-only/][one of the most
reasonable markup languages to use for text]]). But until this point, I've used Hugo (with the ~ox-Hugo~
exporter). It worked fine, but it always seemed /just a little bit too complicated/ for my needs. I
wanted to find something where I could basically understand all of the components and where the gap
between my org-mode files and the published output was as small as possible. I wanted to focus more
on the writing and less on understanding the framework.
** [[file:posts/20211201-resources.org][(2021-12-02) Resources]]
Here are some resources to reference for building a simple site with org-model. I've extensively
used the sites listed as models for building the present site and expect to continue to reference
them for some time.