#+TITLE: Resources
#+DATE: <2021-12-02 Thu>

#+BEGIN_PREVIEW
Here are some resources to reference for building a simple site with org-model. I've extensively
used the sites listed as models for building the present site and expect to continue to reference
them for some time.
#+END_PREVIEW


** [[https://thibaultmarin.github.io/blog/posts/2016-11-13-Personal_website_in_org.html#html_head][Personal Website in Org]]
Good resoures for setting up a custom sitemap as an index page.
** [[https://github.com/gongzhitaao/orgcss][OrgCSS Stylesheet]]
Nice-looking basic stylesheet for site. I likely won't stick with this forever but it looks good for
  now.
** [[https://loomcom.com/blog/0110_emacs_blogging_for_fun_and_profit.html][loomcom]]
This site includes a good overview of making list of posts with previews of the first few lines of
text.
** [[https://ogbe.net/blog/blogging_with_org.html][Blogging using org-mode (and nothing else)]]
By Dennis Ogbe. The code I ultimately used for generating and showing previews closely followed that
from this post.
** [[https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Worg Publishing to HTML Tutorial]]
Good tutorial covering the basics of publishing org-mode projects to html.
** [[https://djliden.github.io/][My Site]]
Here is a link to the site I'm making. Ultimately I will add a custom domain.
