name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Setup GPG for Emacs
      run: |
          # Install GPG and Dirmngr
          sudo apt-get update
          sudo apt-get install -y gnupg2 dirmngr

          # Setup GPG environment
          mkdir -p ~/.emacs.d/elpa/gnupg
          chmod 700 ~/.emacs.d/elpa/gnupg
          gpg --homedir ~/.emacs.d/elpa/gnupg --list-keys

          # Import GPG Key
          gpg2 --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40

      - name: Build the site
        run: ./build.sh

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public